site_name: "Solar2D Bazaar"
copyright: Copyright &copy;2022 develephant
repo_url: ''
theme:
  name: material
  icon: material/white-balance-sunny
  palette:
    scheme: slate
    primary: deep orange
    accent: orange
plugins:
  - simple
  - search