site_name: Solar2D Bazaar
copyright: Copyright &copy;2022 develephant
repo_url: ''
theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  palette:
    scheme: solar2d
extra_css:
  - stylesheets/extra.css
plugins:
  - simple
  - search

